apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  replicas: 5
  template:
    metadata:
      labels: 
        env: nginx-demo
      name: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
  selector:
    matchLabels:
      env: nginx-demo